/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * ServiceReference holds a reference to Service.legacy.k8s.io
 * @export
 * @interface ApiextensionsV1beta1ServiceReference
 */
export default interface ApiextensionsV1beta1ServiceReference extends KubeObject {
  /**
   * name is the name of the service. Required
   * @type {string}
   * @memberof ApiextensionsV1beta1ServiceReference
   */
  name: string

  /**
   * namespace is the namespace of the service. Required
   * @type {string}
   * @memberof ApiextensionsV1beta1ServiceReference
   */
  namespace: string

  /**
   * path is an optional URL path at which the webhook will be contacted.
   * @type {string}
   * @memberof ApiextensionsV1beta1ServiceReference
   */
  path?: string

  /**
   * port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility.
   * @type {number}
   * @memberof ApiextensionsV1beta1ServiceReference
   */
  port?: number
}
