/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * ServiceReference holds a reference to Service.legacy.k8s.io
 * @export
 * @interface ApiregistrationV1ServiceReference
 */
export default interface ApiregistrationV1ServiceReference extends KubeObject {
  /**
   * Name is the name of the service
   * @type {string}
   * @memberof ApiregistrationV1ServiceReference
   */
  name?: string

  /**
   * Namespace is the namespace of the service
   * @type {string}
   * @memberof ApiregistrationV1ServiceReference
   */
  namespace?: string

  /**
   * If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive).
   * @type {number}
   * @memberof ApiregistrationV1ServiceReference
   */
  port?: number
}
