/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import CoreV1Event from './CoreV1Event'
import V1ListMeta from './V1ListMeta'

/**
 * EventList is a list of events.
 * @export
 * @interface CoreV1EventList
 */
export default interface CoreV1EventList extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof CoreV1EventList
   */
  apiVersion?: string

  /**
   * List of events
   * @type {Array<CoreV1Event>}
   * @memberof CoreV1EventList
   */
  items: Array<CoreV1Event>

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof CoreV1EventList
   */
  kind?: string

  /**
   *
   * @type {V1ListMeta}
   * @memberof CoreV1EventList
   */
  metadata?: V1ListMeta
}
