/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 * @export
 * @interface CoreV1EventSeries
 */
export default interface CoreV1EventSeries extends KubeObject {
  /**
   * Number of occurrences in this series up to the last heartbeat time
   * @type {number}
   * @memberof CoreV1EventSeries
   */
  count?: number

  /**
   * Time of the last occurrence observed
   * @type {Date}
   * @memberof CoreV1EventSeries
   */
  lastObservedTime?: Date
}
