/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1alpha1GroupSubject from './V1alpha1GroupSubject'
import V1alpha1ServiceAccountSubject from './V1alpha1ServiceAccountSubject'
import V1alpha1UserSubject from './V1alpha1UserSubject'

/**
 * Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
 * @export
 * @interface FlowcontrolV1alpha1Subject
 */
export default interface FlowcontrolV1alpha1Subject extends KubeObject {
  /**
   *
   * @type {V1alpha1GroupSubject}
   * @memberof FlowcontrolV1alpha1Subject
   */
  group?: V1alpha1GroupSubject

  /**
   * Required
   * @type {string}
   * @memberof FlowcontrolV1alpha1Subject
   */
  kind: string

  /**
   *
   * @type {V1alpha1ServiceAccountSubject}
   * @memberof FlowcontrolV1alpha1Subject
   */
  serviceAccount?: V1alpha1ServiceAccountSubject

  /**
   *
   * @type {V1alpha1UserSubject}
   * @memberof FlowcontrolV1alpha1Subject
   */
  user?: V1alpha1UserSubject
}
