/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import NetworkingV1beta1IngressBackend from './NetworkingV1beta1IngressBackend'
import NetworkingV1beta1IngressRule from './NetworkingV1beta1IngressRule'
import NetworkingV1beta1IngressTLS from './NetworkingV1beta1IngressTLS'

/**
 * IngressSpec describes the Ingress the user wishes to exist.
 * @export
 * @interface NetworkingV1beta1IngressSpec
 */
export default interface NetworkingV1beta1IngressSpec extends KubeObject {
  /**
   *
   * @type {NetworkingV1beta1IngressBackend}
   * @memberof NetworkingV1beta1IngressSpec
   */
  backend?: NetworkingV1beta1IngressBackend

  /**
   * IngressClassName is the name of the IngressClass cluster resource. The associated IngressClass defines which controller will implement the resource. This replaces the deprecated `kubernetes.io/ingress.class` annotation. For backwards compatibility, when that annotation is set, it must be given precedence over this field. The controller may emit a warning if the field and annotation have different values. Implementations of this API should ignore Ingresses without a class specified. An IngressClass resource may be marked as default, which can be used to set a default value for this field. For more information, refer to the IngressClass documentation.
   * @type {string}
   * @memberof NetworkingV1beta1IngressSpec
   */
  ingressClassName?: string

  /**
   * A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.
   * @type {Array<NetworkingV1beta1IngressRule>}
   * @memberof NetworkingV1beta1IngressSpec
   */
  rules?: Array<NetworkingV1beta1IngressRule>

  /**
   * TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI.
   * @type {Array<NetworkingV1beta1IngressTLS>}
   * @memberof NetworkingV1beta1IngressSpec
   */
  tls?: Array<NetworkingV1beta1IngressTLS>
}
