/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * GroupSubject holds detailed information for group-kind subject.
 * @export
 * @interface V1alpha1GroupSubject
 */
export default interface V1alpha1GroupSubject extends KubeObject {
  /**
   * name is the user group that matches, or \"*\" to match all user groups. See https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/user/user.go for some well-known group names. Required.
   * @type {string}
   * @memberof V1alpha1GroupSubject
   */
  name: string
}
