/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1alpha1PriorityLevelConfigurationCondition from './V1alpha1PriorityLevelConfigurationCondition'

/**
 * PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
 * @export
 * @interface V1alpha1PriorityLevelConfigurationStatus
 */
export default interface V1alpha1PriorityLevelConfigurationStatus extends KubeObject {
  /**
   * `conditions` is the current state of \"request-priority\".
   * @type {Array<V1alpha1PriorityLevelConfigurationCondition>}
   * @memberof V1alpha1PriorityLevelConfigurationStatus
   */
  conditions?: Array<V1alpha1PriorityLevelConfigurationCondition>
}
