/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * ServiceAccountSubject holds detailed information for service-account-kind subject.
 * @export
 * @interface V1alpha1ServiceAccountSubject
 */
export default interface V1alpha1ServiceAccountSubject extends KubeObject {
  /**
   * `name` is the name of matching ServiceAccount objects, or \"*\" to match regardless of name. Required.
   * @type {string}
   * @memberof V1alpha1ServiceAccountSubject
   */
  name: string

  /**
   * `namespace` is the namespace of matching ServiceAccount objects. Required.
   * @type {string}
   * @memberof V1alpha1ServiceAccountSubject
   */
  namespace: string
}
