/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * FlowSchemaCondition describes conditions for a FlowSchema.
 * @export
 * @interface V1alpha1FlowSchemaCondition
 */
export default interface V1alpha1FlowSchemaCondition extends KubeObject {
  /**
   * `lastTransitionTime` is the last time the condition transitioned from one status to another.
   * @type {Date}
   * @memberof V1alpha1FlowSchemaCondition
   */
  lastTransitionTime?: Date

  /**
   * `message` is a human-readable message indicating details about last transition.
   * @type {string}
   * @memberof V1alpha1FlowSchemaCondition
   */
  message?: string

  /**
   * `reason` is a unique, one-word, CamelCase reason for the condition\'s last transition.
   * @type {string}
   * @memberof V1alpha1FlowSchemaCondition
   */
  reason?: string

  /**
   * `status` is the status of the condition. Can be True, False, Unknown. Required.
   * @type {string}
   * @memberof V1alpha1FlowSchemaCondition
   */
  status?: string

  /**
   * `type` is the type of the condition. Required.
   * @type {string}
   * @memberof V1alpha1FlowSchemaCondition
   */
  type?: string
}
