/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * UserSubject holds detailed information for user-kind subject.
 * @export
 * @interface V1alpha1UserSubject
 */
export default interface V1alpha1UserSubject extends KubeObject {
  /**
   * `name` is the username that matches, or \"*\" to match all usernames. Required.
   * @type {string}
   * @memberof V1alpha1UserSubject
   */
  name: string
}
