/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1ObjectMeta from './V1ObjectMeta'
import V1alpha1FlowSchemaSpec from './V1alpha1FlowSchemaSpec'
import V1alpha1FlowSchemaStatus from './V1alpha1FlowSchemaStatus'

/**
 * FlowSchema defines the schema of a group of flows. Note that a flow is made up of a set of inbound API requests with similar attributes and is identified by a pair of strings: the name of the FlowSchema and a \"flow distinguisher\".
 * @export
 * @interface V1alpha1FlowSchema
 */
export default interface V1alpha1FlowSchema extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1alpha1FlowSchema
   */
  apiVersion?: string

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1alpha1FlowSchema
   */
  kind?: string

  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1alpha1FlowSchema
   */
  metadata?: V1ObjectMeta

  /**
   *
   * @type {V1alpha1FlowSchemaSpec}
   * @memberof V1alpha1FlowSchema
   */
  spec?: V1alpha1FlowSchemaSpec

  /**
   *
   * @type {V1alpha1FlowSchemaStatus}
   * @memberof V1alpha1FlowSchema
   */
  status?: V1alpha1FlowSchemaStatus
}
