/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * Overhead structure represents the resource overhead associated with running a pod.
 * @export
 * @interface V1alpha1Overhead
 */
export default interface V1alpha1Overhead extends KubeObject {
  /**
   * PodFixed represents the fixed resource overhead associated with running a pod.
   * @type {{ [key: string]: string; }}
   * @memberof V1alpha1Overhead
   */
  podFixed?: { [key: string]: string }
}
