/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1alpha1FlowDistinguisherMethod from './V1alpha1FlowDistinguisherMethod'
import V1alpha1PolicyRulesWithSubjects from './V1alpha1PolicyRulesWithSubjects'
import V1alpha1PriorityLevelConfigurationReference from './V1alpha1PriorityLevelConfigurationReference'

/**
 * FlowSchemaSpec describes how the FlowSchema\'s specification looks like.
 * @export
 * @interface V1alpha1FlowSchemaSpec
 */
export default interface V1alpha1FlowSchemaSpec extends KubeObject {
  /**
   *
   * @type {V1alpha1FlowDistinguisherMethod}
   * @memberof V1alpha1FlowSchemaSpec
   */
  distinguisherMethod?: V1alpha1FlowDistinguisherMethod

  /**
   * `matchingPrecedence` is used to choose among the FlowSchemas that match a given request. The chosen FlowSchema is among those with the numerically lowest (which we take to be logically highest) MatchingPrecedence.  Each MatchingPrecedence value must be ranged in [1,10000]. Note that if the precedence is not specified, it will be set to 1000 as default.
   * @type {number}
   * @memberof V1alpha1FlowSchemaSpec
   */
  matchingPrecedence?: number

  /**
   *
   * @type {V1alpha1PriorityLevelConfigurationReference}
   * @memberof V1alpha1FlowSchemaSpec
   */
  priorityLevelConfiguration: V1alpha1PriorityLevelConfigurationReference

  /**
   * `rules` describes which requests will match this flow schema. This FlowSchema matches a request if and only if at least one member of rules matches the request. if it is an empty slice, there will be no requests matching the FlowSchema.
   * @type {Array<V1alpha1PolicyRulesWithSubjects>}
   * @memberof V1alpha1FlowSchemaSpec
   */
  rules?: Array<V1alpha1PolicyRulesWithSubjects>
}
