/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1ObjectMeta from './V1ObjectMeta'
import V1alpha1AggregationRule from './V1alpha1AggregationRule'
import V1alpha1PolicyRule from './V1alpha1PolicyRule'

/**
 * ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 ClusterRole, and will no longer be served in v1.22.
 * @export
 * @interface V1alpha1ClusterRole
 */
export default interface V1alpha1ClusterRole extends KubeObject {
  /**
   *
   * @type {V1alpha1AggregationRule}
   * @memberof V1alpha1ClusterRole
   */
  aggregationRule?: V1alpha1AggregationRule

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1alpha1ClusterRole
   */
  apiVersion?: string

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1alpha1ClusterRole
   */
  kind?: string

  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1alpha1ClusterRole
   */
  metadata?: V1ObjectMeta

  /**
   * Rules holds all the PolicyRules for this ClusterRole
   * @type {Array<V1alpha1PolicyRule>}
   * @memberof V1alpha1ClusterRole
   */
  rules?: Array<V1alpha1PolicyRule>
}
