/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * FlowDistinguisherMethod specifies the method of a flow distinguisher.
 * @export
 * @interface V1alpha1FlowDistinguisherMethod
 */
export default interface V1alpha1FlowDistinguisherMethod extends KubeObject {
  /**
   * `type` is the type of flow distinguisher method The supported types are \"ByUser\" and \"ByNamespace\". Required.
   * @type {string}
   * @memberof V1alpha1FlowDistinguisherMethod
   */
  type: string
}
