/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import RbacV1alpha1Subject from './RbacV1alpha1Subject'
import V1ObjectMeta from './V1ObjectMeta'
import V1alpha1RoleRef from './V1alpha1RoleRef'

/**
 * ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 ClusterRoleBinding, and will no longer be served in v1.22.
 * @export
 * @interface V1alpha1ClusterRoleBinding
 */
export default interface V1alpha1ClusterRoleBinding extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1alpha1ClusterRoleBinding
   */
  apiVersion?: string

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1alpha1ClusterRoleBinding
   */
  kind?: string

  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1alpha1ClusterRoleBinding
   */
  metadata?: V1ObjectMeta

  /**
   *
   * @type {V1alpha1RoleRef}
   * @memberof V1alpha1ClusterRoleBinding
   */
  roleRef: V1alpha1RoleRef

  /**
   * Subjects holds references to the objects the role applies to.
   * @type {Array<RbacV1alpha1Subject>}
   * @memberof V1alpha1ClusterRoleBinding
   */
  subjects?: Array<RbacV1alpha1Subject>
}
