/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1TypedLocalObjectReference from './V1TypedLocalObjectReference'

/**
 * IngressClassSpec provides information about the class of an Ingress.
 * @export
 * @interface V1beta1IngressClassSpec
 */
export default interface V1beta1IngressClassSpec extends KubeObject {
  /**
   * Controller refers to the name of the controller that should handle this class. This allows for different \"flavors\" that are controlled by the same controller. For example, you may have different Parameters for the same implementing controller. This should be specified as a domain-prefixed path no more than 250 characters in length, e.g. \"acme.io/ingress-controller\". This field is immutable.
   * @type {string}
   * @memberof V1beta1IngressClassSpec
   */
  controller?: string

  /**
   *
   * @type {V1TypedLocalObjectReference}
   * @memberof V1beta1IngressClassSpec
   */
  parameters?: V1TypedLocalObjectReference
}
