/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * AllowedFlexVolume represents a single Flexvolume that is allowed to be used.
 * @export
 * @interface V1beta1AllowedFlexVolume
 */
export default interface V1beta1AllowedFlexVolume extends KubeObject {
  /**
   * driver is the name of the Flexvolume driver.
   * @type {string}
   * @memberof V1beta1AllowedFlexVolume
   */
  driver: string
}
