/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1beta1CustomResourceDefinitionCondition from './V1beta1CustomResourceDefinitionCondition'
import V1beta1CustomResourceDefinitionNames from './V1beta1CustomResourceDefinitionNames'

/**
 * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
 * @export
 * @interface V1beta1CustomResourceDefinitionStatus
 */
export default interface V1beta1CustomResourceDefinitionStatus extends KubeObject {
  /**
   *
   * @type {V1beta1CustomResourceDefinitionNames}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  acceptedNames?: V1beta1CustomResourceDefinitionNames

  /**
   * conditions indicate state for particular aspects of a CustomResourceDefinition
   * @type {Array<V1beta1CustomResourceDefinitionCondition>}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  conditions?: Array<V1beta1CustomResourceDefinitionCondition>

  /**
   * storedVersions lists all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so a migration controller can finish a migration to another version (ensuring no old objects are left in storage), and then remove the rest of the versions from this list. Versions may not be removed from `spec.versions` while they exist in this list.
   * @type {Array<string>}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  storedVersions?: Array<string>
}
