/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 *
 * @export
 * @interface V1beta1CertificateSigningRequestCondition
 */
export default interface V1beta1CertificateSigningRequestCondition extends KubeObject {
  /**
   * lastTransitionTime is the time the condition last transitioned from one status to another. If unset, when a new condition type is added or an existing condition\'s status is changed, the server defaults this to the current time.
   * @type {Date}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  lastTransitionTime?: Date

  /**
   * timestamp for the last update to this condition
   * @type {Date}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  lastUpdateTime?: Date

  /**
   * human readable message with details about the request state
   * @type {string}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  message?: string

  /**
   * brief reason for the request state
   * @type {string}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  reason?: string

  /**
   * Status of the condition, one of True, False, Unknown. Approved, Denied, and Failed conditions may not be \"False\" or \"Unknown\". Defaults to \"True\". If unset, should be treated as \"True\".
   * @type {string}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  status?: string

  /**
   * type of the condition. Known conditions include \"Approved\", \"Denied\", and \"Failed\".
   * @type {string}
   * @memberof V1beta1CertificateSigningRequestCondition
   */
  type: string
}
