/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1SELinuxOptions from './V1SELinuxOptions'

/**
 * SELinuxStrategyOptions defines the strategy type and any options used to create the strategy.
 * @export
 * @interface V1beta1SELinuxStrategyOptions
 */
export default interface V1beta1SELinuxStrategyOptions extends KubeObject {
  /**
   * rule is the strategy that will dictate the allowable labels that may be set.
   * @type {string}
   * @memberof V1beta1SELinuxStrategyOptions
   */
  rule: string

  /**
   *
   * @type {V1SELinuxOptions}
   * @memberof V1beta1SELinuxStrategyOptions
   */
  seLinuxOptions?: V1SELinuxOptions
}
