/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * EndpointPort represents a Port used by an EndpointSlice
 * @export
 * @interface V1beta1EndpointPort
 */
export default interface V1beta1EndpointPort extends KubeObject {
  /**
   * The application protocol for this port. This field follows standard Kubernetes label syntax. Un-prefixed names are reserved for IANA standard service names (as per RFC-6335 and http://www.iana.org/assignments/service-names). Non-standard protocols should use prefixed names such as mycompany.com/my-custom-protocol.
   * @type {string}
   * @memberof V1beta1EndpointPort
   */
  appProtocol?: string

  /**
   * The name of this port. All ports in an EndpointSlice must have a unique name. If the EndpointSlice is dervied from a Kubernetes service, this corresponds to the Service.ports[].name. Name must either be an empty string or pass DNS_LABEL validation: * must be no more than 63 characters long. * must consist of lower case alphanumeric characters or \'-\'. * must start and end with an alphanumeric character. Default is empty string.
   * @type {string}
   * @memberof V1beta1EndpointPort
   */
  name?: string

  /**
   * The port number of the endpoint. If this is not specified, ports are not restricted and must be interpreted in the context of the specific consumer.
   * @type {number}
   * @memberof V1beta1EndpointPort
   */
  port?: number

  /**
   * The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
   * @type {string}
   * @memberof V1beta1EndpointPort
   */
  protocol?: string
}
