/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * Selects a key from a ConfigMap.
 * @export
 * @interface V1ConfigMapKeySelector
 */
export default interface V1ConfigMapKeySelector extends KubeObject {
  /**
   * The key to select.
   * @type {string}
   * @memberof V1ConfigMapKeySelector
   */
  key: string

  /**
   * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @type {string}
   * @memberof V1ConfigMapKeySelector
   */
  name?: string

  /**
   * Specify whether the ConfigMap or its key must be defined
   * @type {boolean}
   * @memberof V1ConfigMapKeySelector
   */
  optional?: boolean
}
