/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1CustomResourceDefinition from './V1CustomResourceDefinition'
import V1ListMeta from './V1ListMeta'

/**
 * CustomResourceDefinitionList is a list of CustomResourceDefinition objects.
 * @export
 * @interface V1CustomResourceDefinitionList
 */
export default interface V1CustomResourceDefinitionList extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1CustomResourceDefinitionList
   */
  apiVersion?: string

  /**
   * items list individual CustomResourceDefinition objects
   * @type {Array<V1CustomResourceDefinition>}
   * @memberof V1CustomResourceDefinitionList
   */
  items: Array<V1CustomResourceDefinition>

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1CustomResourceDefinitionList
   */
  kind?: string

  /**
   *
   * @type {V1ListMeta}
   * @memberof V1CustomResourceDefinitionList
   */
  metadata?: V1ListMeta
}
