/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * CustomResourceDefinitionCondition contains details for the current condition of this pod.
 * @export
 * @interface V1CustomResourceDefinitionCondition
 */
export default interface V1CustomResourceDefinitionCondition extends KubeObject {
  /**
   * lastTransitionTime last time the condition transitioned from one status to another.
   * @type {Date}
   * @memberof V1CustomResourceDefinitionCondition
   */
  lastTransitionTime?: Date

  /**
   * message is a human-readable message indicating details about last transition.
   * @type {string}
   * @memberof V1CustomResourceDefinitionCondition
   */
  message?: string

  /**
   * reason is a unique, one-word, CamelCase reason for the condition\'s last transition.
   * @type {string}
   * @memberof V1CustomResourceDefinitionCondition
   */
  reason?: string

  /**
   * status is the status of the condition. Can be True, False, Unknown.
   * @type {string}
   * @memberof V1CustomResourceDefinitionCondition
   */
  status: string

  /**
   * type is the type of the condition. Types include Established, NamesAccepted and Terminating.
   * @type {string}
   * @memberof V1CustomResourceDefinitionCondition
   */
  type: string
}
