/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1JSONSchemaProps from './V1JSONSchemaProps'

/**
 * CustomResourceValidation is a list of validation methods for CustomResources.
 * @export
 * @interface V1CustomResourceValidation
 */
export default interface V1CustomResourceValidation extends KubeObject {
  /**
   *
   * @type {V1JSONSchemaProps}
   * @memberof V1CustomResourceValidation
   */
  openAPIV3Schema?: V1JSONSchemaProps
}
