/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1CustomResourceColumnDefinition from './V1CustomResourceColumnDefinition'
import V1CustomResourceSubresources from './V1CustomResourceSubresources'
import V1CustomResourceValidation from './V1CustomResourceValidation'

/**
 * CustomResourceDefinitionVersion describes a version for CRD.
 * @export
 * @interface V1CustomResourceDefinitionVersion
 */
export default interface V1CustomResourceDefinitionVersion extends KubeObject {
  /**
   * additionalPrinterColumns specifies additional columns returned in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for details. If no columns are specified, a single column displaying the age of the custom resource is used.
   * @type {Array<V1CustomResourceColumnDefinition>}
   * @memberof V1CustomResourceDefinitionVersion
   */
  additionalPrinterColumns?: Array<V1CustomResourceColumnDefinition>

  /**
   * deprecated indicates this version of the custom resource API is deprecated. When set to true, API requests to this version receive a warning header in the server response. Defaults to false.
   * @type {boolean}
   * @memberof V1CustomResourceDefinitionVersion
   */
  deprecated?: boolean

  /**
   * deprecationWarning overrides the default warning returned to API clients. May only be set when `deprecated` is true. The default warning indicates this version is deprecated and recommends use of the newest served version of equal or greater stability, if one exists.
   * @type {string}
   * @memberof V1CustomResourceDefinitionVersion
   */
  deprecationWarning?: string

  /**
   * name is the version name, e.g. “v1”, “v2beta1”, etc. The custom resources are served under this version at `/apis/<group>/<version>/...` if `served` is true.
   * @type {string}
   * @memberof V1CustomResourceDefinitionVersion
   */
  name: string

  /**
   *
   * @type {V1CustomResourceValidation}
   * @memberof V1CustomResourceDefinitionVersion
   */
  schema?: V1CustomResourceValidation

  /**
   * served is a flag enabling/disabling this version from being served via REST APIs
   * @type {boolean}
   * @memberof V1CustomResourceDefinitionVersion
   */
  served: boolean

  /**
   * storage indicates this version should be used when persisting custom resources to storage. There must be exactly one version with storage=true.
   * @type {boolean}
   * @memberof V1CustomResourceDefinitionVersion
   */
  storage: boolean

  /**
   *
   * @type {V1CustomResourceSubresources}
   * @memberof V1CustomResourceDefinitionVersion
   */
  subresources?: V1CustomResourceSubresources
}
