/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1WebhookConversion from './V1WebhookConversion'

/**
 * CustomResourceConversion describes how to convert different versions of a CR.
 * @export
 * @interface V1CustomResourceConversion
 */
export default interface V1CustomResourceConversion extends KubeObject {
  /**
   * strategy specifies how custom resources are converted between versions. Allowed values are: - `None`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `Webhook`: API Server will call to an external webhook to do the conversion. Additional information   is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.
   * @type {string}
   * @memberof V1CustomResourceConversion
   */
  strategy: string

  /**
   *
   * @type {V1WebhookConversion}
   * @memberof V1CustomResourceConversion
   */
  webhook?: V1WebhookConversion
}
