/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * EndpointPort is a tuple that describes a single port.
 * @export
 * @interface V1EndpointPort
 */
export default interface V1EndpointPort extends KubeObject {
  /**
   * The application protocol for this port. This field follows standard Kubernetes label syntax. Un-prefixed names are reserved for IANA standard service names (as per RFC-6335 and http://www.iana.org/assignments/service-names). Non-standard protocols should use prefixed names such as mycompany.com/my-custom-protocol. This is a beta field that is guarded by the ServiceAppProtocol feature gate and enabled by default.
   * @type {string}
   * @memberof V1EndpointPort
   */
  appProtocol?: string

  /**
   * The name of this port.  This must match the \'name\' field in the corresponding ServicePort. Must be a DNS_LABEL. Optional only if one port is defined.
   * @type {string}
   * @memberof V1EndpointPort
   */
  name?: string

  /**
   * The port number of the endpoint.
   * @type {number}
   * @memberof V1EndpointPort
   */
  port: number

  /**
   * The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
   * @type {string}
   * @memberof V1EndpointPort
   */
  protocol?: string
}
