/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * ExternalDocumentation allows referencing an external resource for extended documentation.
 * @export
 * @interface V1ExternalDocumentation
 */
export default interface V1ExternalDocumentation extends KubeObject {
  /**
   *
   * @type {string}
   * @memberof V1ExternalDocumentation
   */
  description?: string

  /**
   *
   * @type {string}
   * @memberof V1ExternalDocumentation
   */
  url?: string
}
