/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1HTTPIngressPath from './V1HTTPIngressPath'

/**
 * HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last \'/\' and before the first \'?\' or \'#\'.
 * @export
 * @interface V1HTTPIngressRuleValue
 */
export default interface V1HTTPIngressRuleValue extends KubeObject {
  /**
   * A collection of paths that map requests to backends.
   * @type {Array<V1HTTPIngressPath>}
   * @memberof V1HTTPIngressRuleValue
   */
  paths: Array<V1HTTPIngressPath>
}
