/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1IngressBackend from './V1IngressBackend'
import V1IngressRule from './V1IngressRule'
import V1IngressTLS from './V1IngressTLS'

/**
 * IngressSpec describes the Ingress the user wishes to exist.
 * @export
 * @interface V1IngressSpec
 */
export default interface V1IngressSpec extends KubeObject {
  /**
   *
   * @type {V1IngressBackend}
   * @memberof V1IngressSpec
   */
  defaultBackend?: V1IngressBackend

  /**
   * IngressClassName is the name of the IngressClass cluster resource. The associated IngressClass defines which controller will implement the resource. This replaces the deprecated `kubernetes.io/ingress.class` annotation. For backwards compatibility, when that annotation is set, it must be given precedence over this field. The controller may emit a warning if the field and annotation have different values. Implementations of this API should ignore Ingresses without a class specified. An IngressClass resource may be marked as default, which can be used to set a default value for this field. For more information, refer to the IngressClass documentation.
   * @type {string}
   * @memberof V1IngressSpec
   */
  ingressClassName?: string

  /**
   * A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.
   * @type {Array<V1IngressRule>}
   * @memberof V1IngressSpec
   */
  rules?: Array<V1IngressRule>

  /**
   * TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI.
   * @type {Array<V1IngressTLS>}
   * @memberof V1IngressSpec
   */
  tls?: Array<V1IngressTLS>
}
