/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1IngressSpec from './V1IngressSpec'
import V1IngressStatus from './V1IngressStatus'
import V1ObjectMeta from './V1ObjectMeta'

/**
 * Ingress is a collection of rules that allow inbound connections to reach the endpoints defined by a backend. An Ingress can be configured to give services externally-reachable urls, load balance traffic, terminate SSL, offer name based virtual hosting etc.
 * @export
 * @interface V1Ingress
 */
export default interface V1Ingress extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1Ingress
   */
  apiVersion?: string

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1Ingress
   */
  kind?: string

  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1Ingress
   */
  metadata?: V1ObjectMeta

  /**
   *
   * @type {V1IngressSpec}
   * @memberof V1Ingress
   */
  spec?: V1IngressSpec

  /**
   *
   * @type {V1IngressStatus}
   * @memberof V1Ingress
   */
  status?: V1IngressStatus
}
