/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1IngressServiceBackend from './V1IngressServiceBackend'
import V1TypedLocalObjectReference from './V1TypedLocalObjectReference'

/**
 * IngressBackend describes all endpoints for a given service and port.
 * @export
 * @interface V1IngressBackend
 */
export default interface V1IngressBackend extends KubeObject {
  /**
   *
   * @type {V1TypedLocalObjectReference}
   * @memberof V1IngressBackend
   */
  resource?: V1TypedLocalObjectReference

  /**
   *
   * @type {V1IngressServiceBackend}
   * @memberof V1IngressBackend
   */
  service?: V1IngressServiceBackend
}
