/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1ServiceBackendPort from './V1ServiceBackendPort'

/**
 * IngressServiceBackend references a Kubernetes Service as a Backend.
 * @export
 * @interface V1IngressServiceBackend
 */
export default interface V1IngressServiceBackend extends KubeObject {
  /**
   * Name is the referenced service. The service must exist in the same namespace as the Ingress object.
   * @type {string}
   * @memberof V1IngressServiceBackend
   */
  name: string

  /**
   *
   * @type {V1ServiceBackendPort}
   * @memberof V1IngressServiceBackend
   */
  port?: V1ServiceBackendPort
}
