/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1ObjectMeta from './V1ObjectMeta'
import V1PersistentVolumeClaimSpec from './V1PersistentVolumeClaimSpec'

/**
 * PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
 * @export
 * @interface V1PersistentVolumeClaimTemplate
 */
export default interface V1PersistentVolumeClaimTemplate extends KubeObject {
  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1PersistentVolumeClaimTemplate
   */
  metadata?: V1ObjectMeta

  /**
   *
   * @type {V1PersistentVolumeClaimSpec}
   * @memberof V1PersistentVolumeClaimTemplate
   */
  spec: V1PersistentVolumeClaimSpec
}
