/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * ServiceBackendPort is the service port being referenced.
 * @export
 * @interface V1ServiceBackendPort
 */
export default interface V1ServiceBackendPort extends KubeObject {
  /**
   * Name is the name of the port on the Service. This is a mutually exclusive setting with \"Number\".
   * @type {string}
   * @memberof V1ServiceBackendPort
   */
  name?: string

  /**
   * Number is the numerical port number (e.g. 80) on the Service. This is a mutually exclusive setting with \"Name\".
   * @type {number}
   * @memberof V1ServiceBackendPort
   */
  number?: number
}
