/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * TokenRequestStatus is the result of a token request.
 * @export
 * @interface V1TokenRequestStatus
 */
export default interface V1TokenRequestStatus extends KubeObject {
  /**
   * ExpirationTimestamp is the time of expiration of the returned token.
   * @type {Date}
   * @memberof V1TokenRequestStatus
   */
  expirationTimestamp: Date

  /**
   * Token is the opaque bearer token.
   * @type {string}
   * @memberof V1TokenRequestStatus
   */
  token: string
}
