/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * Event represents a single event to a watched resource.
 * @export
 * @interface V1WatchEvent
 */
export default interface V1WatchEvent extends KubeObject {
  /**
   * Object is:  * If Type is Added or Modified: the new state of the object.  * If Type is Deleted: the state of the object immediately before deletion.  * If Type is Error: *Status is recommended; other types may make sense    depending on context.
   * @type {object}
   * @memberof V1WatchEvent
   */
  object: object

  /**
   *
   * @type {string}
   * @memberof V1WatchEvent
   */
  type: string
}
