/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.19
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import ApiextensionsV1WebhookClientConfig from './ApiextensionsV1WebhookClientConfig'

/**
 * WebhookConversion describes how to call a conversion webhook
 * @export
 * @interface V1WebhookConversion
 */
export default interface V1WebhookConversion extends KubeObject {
  /**
   *
   * @type {ApiextensionsV1WebhookClientConfig}
   * @memberof V1WebhookConversion
   */
  clientConfig?: ApiextensionsV1WebhookClientConfig

  /**
   * conversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail.
   * @type {Array<string>}
   * @memberof V1WebhookConversion
   */
  conversionReviewVersions: Array<string>
}
